/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class DemoApplicationTest {
    @Test fun instanceHasAGetHelloMethod() {
        val instance = DemoApplication()
        assertNotNull(instance.getHello(), "getHelloメソッドを持っている")
    }
    @Test fun getHelloMethodReturnHelloWorldString() {
        val expected = "HelloWorld"
        val actual = DemoApplication().getHello()
        assertEquals(expected, actual, "getHelloメソッドは\"HelloWorld\"を返す")
    }
}
